on:                    # Run the workflow for each of the following event:
    push:                # - A branch is pushed or updated.
      branches:
        - main
    pull_request:        # - A pull-request is openned or updated.
    workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
    release:
      types: [created]   # - A release is created.

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Use the validation build profile to enforce static analysis and coding style.
      - name: Generate Runtimes
        run: |
          ./generate-all.sh

      - name: Cache Runtimes
        uses: actions/cache@v4
        with:
          path: install
          key: runtimes-cache

  build:
    runs-on: ubuntu-latest
    needs: generate

    strategy:
      matrix:
        profile: ["light", "light-tasking", "embedded"]
        target: ["nrf52832", "nrf52833", "nrf52840"]

    steps:
      - uses: actions/checkout@v3

      - uses: alire-project/setup-alire@v1
        with:
          version: 2.0.2

      - name: Restore Generated Runtimes
        uses: actions/cache/restore@v4
        with:
          path: install
          key: runtimes-cache
          fail-on-cache-miss: true

      # Use the validation build profile to enforce static analysis and coding style.
      - name: Build Runtime
        run: |
          cd install/${{ matrix.profile }}-${{ matrix.target }}
          ls -al
          alr build

